require "configurations.options"
require "configurations.keymaps"
require "configurations.plugins"
require "configurations.treesitter"
require "configurations.autopairs"
require "configurations.nvim-tree"
require "configurations.colorscheme"
require "configurations.cmp"
require "configurations.lsp"
require "configurations.comment"
require "configurations.whichkey"
require "configurations.bufferline"
require "configurations.lualine"
require "configurations._telescope"
require "configurations.gitsigns"
-- require "configurations.startup"
